---
# defaults file for docker
remove_docker_olds: 'yes'
docker_gpg_key: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
docker_gpg_id: '9DC858229FC7DD38854AE2D88D81803C0EBFCD88'
docker_repo_rpm_url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/docker-ce.repo"
docker_repo_file: '/etc/apt/sources.list.d/docker.list'
docker_group: 'docker'
docker_completion_url: 'https://raw.githubusercontent.com/docker/docker-ce/master/components/cli/contrib/completion/bash/docker'
docker_completion_path: '/etc/bash_completion.d/docker'
docker_compose_version: '1.26.2'
docker_compose_url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-{{ ansible_architecture }}"
docker_compose_path: '/usr/local/bin/docker-compose'
docker_compose_checksum: 'sha256:13e50875393decdb047993c3c0192b0a3825613e6dfc0fa271efed4f5dbdd6eb'
docker_compose_bash_completion_url: 'https://raw.githubusercontent.com/docker/compose/master/contrib/completion/bash/docker-compose'
docker_compose_bash_completion_path: '/etc/bash_completion.d/docker-compose'
remove_docker: 'false'
common_users:
  - jmadmin
packages_deb_to_remove:
  - docker
  - docker-engine
  - docker.io
  - containerd
  - runc
packages_deps_deb:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
packages_docker_deb:
  - docker-ce
  - docker-ce-cli
  - containerd.io
## CentOS
packages_rpm_to_remove:
  - docker
  - docker-client
  - docker-client-latest
  - docker-common
  - docker-latest
  - docker-latest-logrotate
  - docker-logrotate
  - docker-engine
packages_deps_rpm:
  - yum-utils
  - curl
packages_docker_rpm:
  - docker-ce
  - docker-ce-cli
  - containerd.io
...
