---
# tasks file for monitoringtools
#################################
# Install Node_Exporter
#################################
## Add the Node_exporter Group
- name: Add the Group [{{ node_exporter_group }}] to Handle Node_Exporter Service
  group:
    name: "{{ node_exporter_group }}"
    state: present
  when:
    - remove_node_exporter != 'yes'
  tags:
    - install_node_exporter
    - add_user_node_exporter

## Add the Node_exporter User
- name: Add the user [{{ node_exporter_user }}] to Handle Node_Exporter Service
  user:
    name: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
    shell: "{{ node_exporter_shell }}"
    create_home: no
  when:
    - remove_node_exporter != 'yes'
  tags:
    - install_node_exporter
    - add_group_node_exporter

## Downloading the Node_exporter
- name: Download Node_Exporter
  get_url:
    url: "{{ node_exporter_pkg_url }}"
    dest: "{{ node_exporter_pkg_path }}"
    mode: '0644'
    checksum: "{{ node_exporter_checksum }}"
  when:
    - node_exporter_install == 'yes'
    - remove_node_exporter != 'yes'
  tags:
    - install_node_exporter
    - download_node_exporter

## Unarchive the Node_exporter package
- name: Unarchive Node_Exporter
  unarchive:
    src: "{{ node_exporter_pkg_path }}"
    dest: /tmp
    remote_src: yes
  when:
    - remove_node_exporter != 'yes'
  tags:
    - install_node_exporter
    - unarchive_node_exporter

## Copying the Node_exporter binary file to the correct location
- name: Copy the Node_Exporter Binary
  copy:
    src: "{{ node_exporter_extracted_path }}"
    dest: "{{ node_exporter_bin_path }}"
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
    mode: '0755'
    remote_src: yes
  when:
    - remove_node_exporter != 'yes'
  tags:
    - install_node_exporter
    - copy_binary_node_exporter

## Creating the node_exporter.service
- name: Template {{ node_exporter_systemd }}
  template:
    src: templates/node_exporter.service.j2
    dest: "{{ node_exporter_systemd }}"
    force: yes
    mode: '0644'
    owner: root
    group: root
  when:
    - remove_node_exporter != 'yes'
  notify:
    - Enabling Node_Exporter
    - Start Node_Exporter
  tags:
    - install_node_exporter
    - creating_service_node_exporter

## Removing the Temp Files
- name: Remove the Node_Exporter Temp Files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ node_exporter_extracted_dir }}"
    - "{{ node_exporter_pkg_path }}"
  when:
    - remove_node_exporter != 'yes'
  tags:
    - install_node_exporter
    - remove_temp_files_node_exporter

#################################
# Remove Node_Exporter
#################################
## Remove the Node_exporter binary files and notify the handlers to remove the dependencies
- name: Remove file {{ node_exporter_bin_path }}
  file:
    path: "{{ node_exporter_bin_path }}"
    state: absent
  when:
    - remove_node_exporter == 'yes'
  tags:
    - remove_node_exporter
  notify:
    - Stop Node_Exporter
    - Disabling Node_Exporter
    - Remove file Node_Exporter

