---
# tasks file for docker
- name: Adding Tasks for Debian Base
  import_tasks: debian_base.yml
  when: ansible_distribution_file_variety == 'Debian'
- name: Adding Tasks for RedHat Base
  import_tasks: redhat_base.yml
  when: ansible_distribution_file_variety == 'RedHat'
...