---
# tasks file for zabbix_agent

## List all the files to handle
- name: Find Zabbix Agent Files
  find:
    paths: 
      - /etc/zabbix
    file_type: file
    patterns: '*'
    recurse: yes
  register: files_to_backup
  tags:
    - zbx_bkp_files

## Backup the Files before delete
- name: Backup Zabbix Agent Files
  fetch:
    src: "{{ item.path }}"
    dest: "{{ zbx_bkp_dir }}"
  with_items: "{{ files_to_backup.files }}"
  tags:
    - zbx_bkp_files

- name: Remove Packages on CentOS
  yum:
    name: "{{ packages_to_remove }}"
    state: absent
    autoremove: yes
  when: ansible_distribution == 'CentOS'
  tags:
    - zbx_remove_from_centos
    - zbx_remove

- name: Remove Packages on Ubuntu
  apt:
    name: "{{ packages_to_remove }}"
    state: absent
    purge: yes
    autoremove: yes
  when: ansible_distribution_file_variety == 'Debian'
  tags:
    - zbx_remove_from_debian_base
    - zbx_remove

- name: Clean useless packages from the cache
  apt:
    autoclean: yes
  when: ansible_distribution_file_variety == 'Debian'
  tags:
    - zbx_remove_from_debian_base
    - zbx_remove_cli

- name: Install Zabbix Release on CentOS
  yum:
    name: "{{ zbx_release_rpm }}"
    state: present
  when: ansible_distribution == 'CentOS'
  tags:
    - zbx_install_release_on_centos
    - zbx_install_release

- name: Install Zabbix Release on Ubuntu
  apt:
    deb: "{{ zbx_release_deb }}"
    state: present
  when: ansible_distribution_file_variety == 'Debian'
  tags:
    - zbx_install_release_on_debian_base
    - zbx_install_release

- name: Install Zabbix Agent on Ubuntu
  apt:
    name: "{{ zbx_packages }}"
    update_cache: yes
    state: present
  when: ansible_distribution_file_variety == 'Debian'
  notify: Stop Zabbix Agent
  tags:
    - zbx_install_cli_on_debian_base
    - zbx_install_cli

- name: Install Zabbix Agent on CentOS
  yum:
    name: "{{ zbx_packages }}"
    update_cache: yes
    state: present
  when: ansible_distribution == 'CentOS'
  notify: Stop Zabbix Agent
  tags:
    - zbx_install_cli_on_centos
    - zbx_install_cli

- name: Enable Zabbix Agent
  systemd:
    name: zabbix-agent
    enabled: yes
    masked: no
  tags:
    - zbx_enable_cli

## List all the files to handle
- name: Find Zabbix Agent Files
  find:
    paths: 
      - /etc/zabbix
    file_type: file
    patterns: '*'
    recurse: yes
  register: files_to_delete
  tags:
    - zbx_delete_defaults

# - name: Check the files to Handle
#   debug:
#     var: item.path
#   with_items: "{{ files_to_delete.files }}"

## Remove Custom files
- name: Remove Custom files for Zabbix Agent
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ files_to_delete.files }}"
  tags:
    - zbx_delete_defaults

## Creating the Custom File Directory
- name: Creating the Zabbix Agent Custom File Directory
  file:
    path: "{{ zbx_include_dir }}"
    state: directory
  tags:
    - zbx_config_cli

## Configure the Zabbix Agent
- name: Template zabbix_agentd.conf
  template:
    src: templates/zabbix_agentd.conf.j2
    dest: "{{ zbx_agent_file }}"
    backup: yes
    force: yes
    mode: '0644'
    owner: root
    group: root
  notify: Restart Zabbix Agent
  tags:
    - zbx_config_cli