---
# defaults file for zabbix_agent
zbx_release_rpm: https://repo.zabbix.com/zabbix/4.4/rhel/{{ ansible_distribution_major_version }}/x86_64/zabbix-release-4.4-1.el{{ ansible_distribution_major_version }}.noarch.rpm
zbx_release_deb: https://repo.zabbix.com/zabbix/4.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_4.4-1+{{ ansible_distribution_release }}_all.deb
zbx_agent_file: '/etc/zabbix/zabbix_agentd.conf'
zbx_pid_file: '/var/run/zabbix/zabbix_agentd.pid'
zbx_log_file: '/var/log/zabbix/zabbix_agentd.log'
zbx_log_file_size: '0'
zbx_server: '127.0.0.1'
zbx_agent_port: '10050'
zbx_start_agent: '3'
zbx_refresh_active_checks: '120'
zbx_buffer_send: '5'
zbx_buffer_size: '100'
zbx_max_line_per_seconds: '100'
zbx_timeout: '3'
zbx_include_dir: '/etc/zabbix/zabbix_agentd.d'
zbx_include_files: "{{ zbx_include_dir }}/*.conf"
zbx_bkp_dir: "./bkp/{{ ansible_date_time.date }}-{{ ansible_date_time.hour }}-{{ ansible_date_time.minute }}"
zbx_packages:
  - zabbix-sender
  - zabbix-agent
packages_to_remove:
  - puppet6-release
  - puppet-agent
  - zabbix-agent
  - zabbix-release
  - zabbix-sender
...