---
# defaults file for zabbix_agent
# By default the Zabbix Agent will be not installed if call the role
zabbix_install: false
## Zabbix Agent Remove old Packages
zabbix_remove_olds: true
## Remove Zabbix Agent Flag. Set to true to Remove Zabbix Agent from the System
remove_zabbix: false
## Zabbix Agent Backup Files
zabbix_backup_files: true
## Zabbix Release RPM Package
zabbix_release_rpm: https://repo.zabbix.com/zabbix/4.4/rhel/{{ ansible_distribution_major_version }}/x86_64/zabbix-release-4.4-1.el{{ ansible_distribution_major_version }}.noarch.rpm
## Zabbix Release DEB Package
zabbix_release_deb: https://repo.zabbix.com/zabbix/4.4/{{ ansible_distribution | lower }}/pool/main/z/zabbix-release/zabbix-release_4.4-1+{{ ansible_distribution_release }}_all.deb
## Zabbix Agent Configuration file
zabbix_agent_file: '/etc/zabbix/zabbix_agentd.conf'
## Zabbix Agent PID file
zabbix_pid_file: '/var/run/zabbix/zabbix_agentd.pid'
## Zabbix Agent Log file
zabbix_log_file: '/var/log/zabbix/zabbix_agentd.log'
## Zabbix Agent Log file Size
zabbix_log_file_size: '0'
## Zabbix Server DNS or IP
zabbix_server: '127.0.0.1'
## Zabbix Agent Port
zabbix_agent_port: '10050'
## Zabbix Agent Agents
zabbix_start_agent: '3'
## Zabbix Agent Active Check if Enabled
zabbix_refresh_active_checks: '120'
## Zabbix Agent Buffer Send
zabbix_buffer_send: '5'
## Zabbix Agent Buffer Size
zabbix_buffer_size: '100'
## Zabbix Agent Max lines per second
zabbix_max_line_per_seconds: '100'
## Zabbix Agent Timeout
zabbix_timeout: '3'
## Zabbix Agent Additional configuration files directory
zabbix_include_dir: '/etc/zabbix/zabbix_agentd.d'
## Zabbix Agent Additional configuration files
zabbix_include_files: "{{ zabbix_include_dir }}/*.conf"
## Zabbix Agent Backup Files
zabbix_bkp_dir: "./bkp/{{ ansible_date_time.date }}-{{ ansible_date_time.hour }}-{{ ansible_date_time.minute }}"
## Zabbix Agent Packages
zabbix_packages:
  - zabbix-sender
  - zabbix-agent
## Packages to Remove Before install the Zabbix Agent
packages_to_remove:
  - puppet6-release
  - puppet-agent
  - zabbix-agent
  - zabbix-release
  - zabbix-sender
...
