---
# Tasks file for Role Docker and OS Debian Base

########################################
## Install Docker Tasks
########################################
## Importing the GPG Key
- name: Add an Apt signing key for Docker on Ubuntu/Debian
  apt_key:
    id: "{{ docker_gpg_id }}"
    url: "{{ docker_gpg_key }}"
    state: present
  when:
    - ansible_distribution_file_variety == 'Debian'
    - docker_install == true
    - remove_docker == false
  tags:
    - docker
    - docker_install
    - docker_install_on_debian_base

## Remove the old packages
- name: Remove Old Docker Packages on Ubuntu/Debian
  apt:
    name: "{{ item }}"
    state: absent
    purge: yes
    autoremove: yes
  with_items:
    - "{{ packages_deb_to_remove }}"
  notify:
    - Remove useless packages from the cache on Ubuntu/Debian
    - Remove dependencies that are no longer required on Ubuntu/Debian
  when:
    - ansible_distribution_file_variety == 'Debian'
    - remove_docker_olds == true
    - docker_install == true
    - remove_docker == false
  tags:
    - docker
    - docker_install
    - docker_install_on_debian_base

## Install Dependencies
- name: Install Docker Dependencies on Ubuntu/Debian
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - "{{ packages_deps_deb }}"
  when:
    - ansible_distribution_file_variety == 'Debian'
    - docker_install == true
    - remove_docker == false
  tags:
    - docker
    - docker_install
    - docker_install_on_debian_base

## Configure the Repository
- name: Template for Docker Repository [docker.lists] on Ubuntu/Debian
  template:
    src: templates/docker.lists.j2
    dest: "{{ docker_repo_file }}"
    backup: yes
    force: yes
    mode: '0644'
    owner: 'root'
    group: 'root'
  when:
    - ansible_distribution_file_variety == 'Debian'
    - docker_install == true
    - remove_docker == false
  tags:
    - docker
    - docker_install
    - docker_install_on_debian_base

## Install Docker
- name: Install Docker on Ubuntu/Debian
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - "{{ packages_docker_deb }}"
  when:
    - ansible_distribution_file_variety == 'Debian'
    - docker_install == true
    - remove_docker == false
  notify:
    - Adding common user into group docker
    - Enabling Docker
    - Download Docker completion
    - Download Docker Compose file with check (sha256)
    - Download Docker Compose completion
  tags:
    - docker
    - docker_install
    - docker_install_on_debian_base

########################################
## Remove Docker Tasks
########################################
## Remover Docker
- name: Remove Docker on Ubuntu/Debian
  apt:
    name: "{{ item }}"
    state: absent
    purge: yes
  with_items:
    - "{{ packages_docker_deb }}"
  when:
    - ansible_distribution_file_variety == 'Debian'
    - remove_docker != false
  notify:
    - Remove useless packages from the cache on Ubuntu/Debian
    - Remove dependencies that are no longer required on Ubuntu/Debian
    - Delete Docker completion Files
  tags:
    - docker
    - docker_remove_on_debian_base
...