---
# tasks file for docker

## Importing the GPG Key
- name: Add an Apt signing key for Docker on Ubuntu/Debian
  apt_key:
    id: "{{ docker_gpg_id }}"
    url: "{{ docker_gpg_key }}"
    state: present
  when:
    - ansible_distribution_file_variety == 'Debian'
  tags:
    - docker
    - docker_add_repo_key
    - docker_conf_repo
    - docker_install

## Remove the old packages
- name: Remove Packages on Ubuntu/Debian
  apt:
    name: "{{ item }}"
    state: absent
    purge: yes
    autoremove: yes
  with_items:
    - "{{ packages_deb_to_remove }}"
  when:
    - ansible_distribution_file_variety == 'Debian'
    - remove_docker_olds == 'yes'
  tags:
    - docker
    - docker_remove_from_debian_base
    - docker_remove

- name: Clean useless packages from the cache on Ubuntu/Debian
  apt:
    autoclean: yes
  when:
    - ansible_distribution_file_variety == 'Debian'
    - remove_docker_olds == 'yes'
  tags:
    - docker
    - docker_remove_from_debian_base
    - docker_clean_packages

## Install Dependencies
- name: Install Docker Dependencies on Ubuntu/Debian
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - "{{ packages_deps_deb }}"
  when:
    - ansible_distribution_file_variety == 'Debian'
  tags:
    - docker
    - docker_install_deps_on_debian_base
    - docker_install

## Configure the Repository
- name: Template for Repository docker.lists on Ubuntu/Debian
  template:
    src: templates/docker.lists.j2
    dest: "{{ docker_repo_file }}"
    backup: yes
    force: yes
    mode: '0644'
    owner: root
    group: root
  when:
    - ansible_distribution_file_variety == 'Debian'
  tags:
    - docker
    - docker_conf_repo
    - docker_install

## Install Docker
- name: Install Docker on Ubuntu/Debian
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - "{{ packages_docker_deb }}"
  when:
    - ansible_distribution_file_variety == 'Debian'
  tags:
    - docker
    - docker_install_on_debian_base
    - docker_install

- name: Download Docker completion
  get_url:
    url: "{{ docker_completion_url }}"
    dest: "{{ docker_completion_path }}"
    mode: '0644'
  when:
    - ansible_distribution_file_variety == 'Debian'
  tags:
    - docker
    - docker_compose_install
    - docker_install

## Add users into docker group
- name: Adding common user into group docker
  user:
    name: '{{ item }}'
    groups: docker
    append: yes
  with_items:
    - "{{ common_users }}"
  tags:
    - docker
    - docker_add_user_to_group
    - docker_install

## Enabling and starting the service
- name: Enabling Docker
  systemd:
    name: docker
    enabled: yes
    masked: no
  tags:
    - docker
    - docker_enabled
    - docker_install

## Docker composer
- name: Download Docker Compose file with check (sha256)
  get_url:
    url: "{{ docker_compose_url }}"
    dest: "{{ docker_compose_path }}"
    mode: '0755'
    checksum: "{{ docker_compose_checksum }}"
  when:
    - ansible_distribution_file_variety == 'Debian'
  tags:
    - docker
    - docker_compose_install
    - docker_install

- name: Download Docker Compose completion
  get_url:
    url: "{{ docker_compose_bash_completion_url }}"
    dest: "{{ docker_compose_bash_completion_path }}"
    mode: '0644'
  when:
    - ansible_distribution_file_variety == 'Debian'
  tags:
    - docker
    - docker_compose_install
    - docker_install
...